sudo: false
language: python
python:
    - '3.8'

script:
    - pip install -r requirements.txt
    - travis-sphinx build -n -s docs

after_success:
    - travis-sphinx deploy -b gh-[ages]
